fix: Close NATS Streaming connections instead of subscriptions
To work around https://console.cloud.google.com/errors/detail/CNzUjrq62b2GGw?project=gw-frankfurt-4065

```
 Error: stan: invalid subscription
    at Object.callback (/opt/gw/node_modules/node-nats-streaming/lib/stan.js:858:26)
    at Object.callback (/opt/gw/node_modules/nats/lib/nats.js:2045:16)
    at Client.processMsg (/opt/gw/node_modules/nats/lib/nats.js:1437:13)
    at Client.processInbound (/opt/gw/node_modules/nats/lib/nats.js:1310:14)
    at Socket.<anonymous> (/opt/gw/node_modules/nats/lib/nats.js:820:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
```