chore(deps): Bump mongodb from 4.14.0 to 4.17.1 (#1057)
Bumps [mongodb](https://github.com/mongodb/node-mongodb-native) from 4.14.0 to 4.17.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/mongodb/node-mongodb-native/releases">mongodb's releases</a>.</em></p>
<blockquote>
<h2>v4.17.1</h2>
<h2><a href="https://github.com/mongodb/node-mongodb-native/compare/v4.17.0...v4.17.1">4.17.1</a> (2023-08-23)</h2>
<p>The MongoDB Node.js team is pleased to announce version 4.17.1 of the <code>mongodb</code> package!</p>
<h2>Release Notes</h2>
<h3>Import of <code>saslprep</code> updated to correct library.</h3>
<p>Fixes the import of saslprep to be the correct <code>@mongodb-js/saslprep</code> library.</p>
<h3>Bug Fixes</h3>
<ul>
<li><strong>NODE-5573:</strong> fix saslprep import (<a href="https://redirect.github.com/mongodb/node-mongodb-native/issues/3838">#3838</a>) (<a href="https://github.com/mongodb/node-mongodb-native/commit/ff6c2938b8739f0bd0b1ca6271095c5563a5a408">ff6c293</a>)</li>
</ul>
<h2>Documentation</h2>
<ul>
<li><a href="https://docs.mongodb.com/drivers/node/current/">Reference</a></li>
<li><a href="https://mongodb.github.io/node-mongodb-native/4.17/">API</a></li>
<li><a href="https://github.com/mongodb/node-mongodb-native/blob/v4.17.1/HISTORY.md">Changelog</a></li>
</ul>
<p>We invite you to try the <code>mongodb</code> library immediately, and report any issues to the <a href="https://jira.mongodb.org/projects/NODE">NODE project</a>.</p>
<h2>v4.17.0</h2>
<h2><a href="https://github.com/mongodb/node-mongodb-native/compare/v4.16.0...v4.17.0">4.17.0</a> (2023-08-17)</h2>
<p>The MongoDB Node.js team is pleased to announce version 4.17.0 of the <code>mongodb</code> package!</p>
<h2>Release Notes</h2>
<h3><code>mongodb-js/saslprep</code> is now installed by default</h3>
<p>Until v6, the driver included the <code>saslprep</code> package as an optional dependency for SCRAM-SHA-256 authentication.  <code>saslprep</code> breaks when bundled with webpack because it attempted to read a file relative to the package location and consequently the driver would throw errors when using SCRAM-SHA-256 if it were bundled.</p>
<p>The driver now depends on <code>mongodb-js/saslprep</code>, a fork of <code>saslprep</code> that can be bundled with webpack because it includes the necessary saslprep data in memory upon loading. This will be installed by default but will only be used if SCRAM-SHA-256 authentication is used.</p>
<h3>Remove credential availability on <code>ConnectionPoolCreatedEvent</code></h3>
<p>In order to avoid mistakenly printing credentials the <code>ConnectionPoolCreatedEvent</code> will replace the credentials option with an empty object. The credentials are still accessble via MongoClient options: <code>client.options.credentials</code>.</p>
<h3>Features</h3>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/mongodb/node-mongodb-native/blob/v4.17.1/HISTORY.md">mongodb's changelog</a>.</em></p>
<blockquote>
<h2><a href="https://github.com/mongodb/node-mongodb-native/compare/v4.17.0...v4.17.1">4.17.1</a> (2023-08-23)</h2>
<h3>Bug Fixes</h3>
<ul>
<li><strong>NODE-5573:</strong> fix saslprep import (<a href="https://redirect.github.com/mongodb/node-mongodb-native/issues/3838">#3838</a>) (<a href="https://github.com/mongodb/node-mongodb-native/commit/ff6c2938b8739f0bd0b1ca6271095c5563a5a408">ff6c293</a>)</li>
</ul>
<h2><a href="https://github.com/mongodb/node-mongodb-native/compare/v4.16.0...v4.17.0">4.17.0</a> (2023-08-17)</h2>
<h3>Features</h3>
<ul>
<li><strong>NODE-5272:</strong> do not create or drop ecc collections (<a href="https://redirect.github.com/mongodb/node-mongodb-native/issues/3678">#3678</a>) (<a href="https://github.com/mongodb/node-mongodb-native/commit/d26ad6166ae58c9976770eec84f32f9c2c17a0f3">d26ad61</a>)</li>
<li><strong>NODE-5398:</strong> use mongodb-js/saslprep instead of saslprep (<a href="https://redirect.github.com/mongodb/node-mongodb-native/issues/3820">#3820</a>) (<a href="https://github.com/mongodb/node-mongodb-native/commit/5244711723cc7b05c50dac6ba4b7363b5af2ac37">5244711</a>)</li>
</ul>
<h3>Bug Fixes</h3>
<ul>
<li><strong>NODE-5262:</strong> AWS Lambda metadata detection logic is too permissive (<a href="https://redirect.github.com/mongodb/node-mongodb-native/issues/3683">#3683</a>) (<a href="https://github.com/mongodb/node-mongodb-native/commit/c0c3d99784fc487f1cbe0eb02a63c58a1242d872">c0c3d99</a>)</li>
<li><strong>NODE-5311:</strong> construct error messages for AggregateErrors in Node16+ (<a href="https://redirect.github.com/mongodb/node-mongodb-native/issues/3683">#3683</a>) (<a href="https://github.com/mongodb/node-mongodb-native/commit/98b7bdf2d6c08ba9470bbda0fad3251ea0a08949">98b7bdf</a>)</li>
<li><strong>NODE-5316:</strong> prevent parallel topology creation in MongoClient.connect (<a href="https://redirect.github.com/mongodb/node-mongodb-native/issues/3696">#3696</a>) (<a href="https://github.com/mongodb/node-mongodb-native/commit/e13038d1c7246e95b32993fc97331713b542fd74">e13038d</a>)</li>
<li><strong>NODE-5356:</strong> prevent scram auth from throwing TypeError if saslprep is not a function (<a href="https://redirect.github.com/mongodb/node-mongodb-native/issues/3732">#3732</a>) (<a href="https://github.com/mongodb/node-mongodb-native/commit/2d028af31d17a25a16c1ef73749a266fe7cf3a33">2d028af</a>)</li>
<li><strong>NODE-5536:</strong> remove credentials from ConnectionPoolCreatedEvent options (<a href="https://redirect.github.com/mongodb/node-mongodb-native/issues/3812">#3812</a>) (<a href="https://github.com/mongodb/node-mongodb-native/commit/2910dcae38ce29e0ee5afc497ac146de2a4bb984">2910dca</a>)</li>
</ul>
<h2><a href="https://github.com/mongodb/node-mongodb-native/compare/v4.15.0...v4.16.0">4.16.0</a> (2023-04-18)</h2>
<h3>Features</h3>
<ul>
<li><strong>NODE-5159:</strong> add FaaS env information to client metadata (<a href="https://redirect.github.com/mongodb/node-mongodb-native/issues/3639">#3639</a>) (<a href="https://github.com/mongodb/node-mongodb-native/commit/e0b20f1ba4c0d8826077703a3cd77936b9be7dfd">e0b20f1</a>)</li>
<li><strong>NODE-5199:</strong> add alternative runtime detection to client metadata (<a href="https://redirect.github.com/mongodb/node-mongodb-native/issues/3647">#3647</a>) (<a href="https://github.com/mongodb/node-mongodb-native/commit/fba16adb52f2ef37e87ea64bd6163711d0f09b84">fba16ad</a>)</li>
</ul>
<h3>Bug Fixes</h3>
<ul>
<li><strong>NODE-5161:</strong> metadata duplication in handshake (<a href="https://redirect.github.com/mongodb/node-mongodb-native/issues/3628">#3628</a>) (<a href="https://github.com/mongodb/node-mongodb-native/commit/b79014286c714291a1d16f12c6397e545411da0f">b790142</a>)</li>
<li><strong>NODE-5200:</strong> relax SRV record validation to account for a dot suffix (<a href="https://redirect.github.com/mongodb/node-mongodb-native/issues/3640">#3640</a>) (<a href="https://github.com/mongodb/node-mongodb-native/commit/4272c43aed8790edcc38c69004e227c97117076a">4272c43</a>)</li>
</ul>
<h2><a href="https://github.com/mongodb/node-mongodb-native/compare/v4.14.0...v4.15.0">4.15.0</a> (2023-04-04)</h2>
<h3>Features</h3>
<ul>
<li><strong>NODE-5054:</strong> add AssumeRoleWithWebIdentity support to 4x driver (<a href="https://redirect.github.com/mongodb/node-mongodb-native/issues/3566">#3566</a>) (<a href="https://github.com/mongodb/node-mongodb-native/commit/8a8c386a8dc9263aa68826a8705c7800752a7153">8a8c386</a>)</li>
</ul>
<h3>Bug Fixes</h3>
<ul>
<li><strong>NODE-5097:</strong> set timeout on write and reset on message (<a href="https://redirect.github.com/mongodb/node-mongodb-native/issues/3590">#3590</a>) (<a href="https://github.com/mongodb/node-mongodb-native/commit/2d3576bf154843f0b8f63710c530d07cdc7a2ea6">2d3576b</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/mongodb/node-mongodb-native/commit/cdc3d53f26d0701a22337025e2e96fda070badb6"><code>cdc3d53</code></a> chore(4.x): release 4.17.1 [skip-ci] (<a href="https://redirect.github.com/mongodb/node-mongodb-native/issues/3840">#3840</a>)</li>
<li><a href="https://github.com/mongodb/node-mongodb-native/commit/ff6c2938b8739f0bd0b1ca6271095c5563a5a408"><code>ff6c293</code></a> fix(NODE-5573): fix saslprep import (<a href="https://redirect.github.com/mongodb/node-mongodb-native/issues/3838">#3838</a>)</li>
<li><a href="https://github.com/mongodb/node-mongodb-native/commit/c83a801a8375131c0d2327d9c9e6f50ed6600008"><code>c83a801</code></a> chore(4.x): release 4.17.0 [skip-ci] (<a href="https://redirect.github.com/mongodb/node-mongodb-native/issues/3763">#3763</a>)</li>
<li><a href="https://github.com/mongodb/node-mongodb-native/commit/1b599558f012597ee0cb6ed8595aceb38757bbb1"><code>1b59955</code></a> chore: update release automation scripts 4.x (<a href="https://redirect.github.com/mongodb/node-mongodb-native/issues/3824">#3824</a>)</li>
<li><a href="https://github.com/mongodb/node-mongodb-native/commit/5244711723cc7b05c50dac6ba4b7363b5af2ac37"><code>5244711</code></a> feat(NODE-5398): use mongodb-js/saslprep instead of saslprep (<a href="https://redirect.github.com/mongodb/node-mongodb-native/issues/3820">#3820</a>)</li>
<li><a href="https://github.com/mongodb/node-mongodb-native/commit/2910dcae38ce29e0ee5afc497ac146de2a4bb984"><code>2910dca</code></a> fix(NODE-5536): remove credentials from ConnectionPoolCreatedEvent options (#...</li>
<li><a href="https://github.com/mongodb/node-mongodb-native/commit/0c1b654406f781c5cf78149a16f9ed7c3057ae1f"><code>0c1b654</code></a> chore(NODE-5400): add <code>@​octokit/core</code> as a devDep (<a href="https://redirect.github.com/mongodb/node-mongodb-native/issues/3750">#3750</a>)</li>
<li><a href="https://github.com/mongodb/node-mongodb-native/commit/4adff378f175aaa0bf76211bb96d79d5627fecf4"><code>4adff37</code></a> chore(NODE-5382): backport release automation scripts (<a href="https://redirect.github.com/mongodb/node-mongodb-native/issues/3747">#3747</a>)</li>
<li><a href="https://github.com/mongodb/node-mongodb-native/commit/2d028af31d17a25a16c1ef73749a266fe7cf3a33"><code>2d028af</code></a> fix(NODE-5356): prevent scram auth from throwing TypeError if saslprep is not...</li>
<li><a href="https://github.com/mongodb/node-mongodb-native/commit/0e1afc04d0c688857bdcde24c73224fd054ce1b3"><code>0e1afc0</code></a> ci(Node 5335): clean up instance profile from instance after CI runs (<a href="https://redirect.github.com/mongodb/node-mongodb-native/issues/3719">#3719</a>)</li>
<li>Additional commits viewable in <a href="https://github.com/mongodb/node-mongodb-native/compare/v4.14.0...v4.17.1">compare view</a></li>
</ul>
</details>
<details>
<summary>Maintainer changes</summary>
<p>This version was pushed to npm by <a href="https://www.npmjs.com/~dbx-node">dbx-node</a>, a new releaser for mongodb since your current version.</p>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=mongodb&package-manager=npm_and_yarn&previous-version=4.14.0&new-version=4.17.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)
You can disable automated security fix PRs for this repo from the [Security Alerts page](https://github.com/relaycorp/relaynet-internet-gateway/network/alerts).

</details>